[package]
name = "arca-server"
version.workspace = true
edition = "2021"
description = "Arca S3-compatible object storage server"

[[bin]]
name = "arca"
path = "src/main.rs"

[dependencies]
arca-core = { workspace = true }
async-trait = { workspace = true }
arca-auth = { workspace = true }
arca-storage = { workspace = true, features = ["postgres"] }
arca-proto = { workspace = true }
anyhow = { workspace = true }
axum = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
toml = { workspace = true }
tower = { workspace = true }
hex = { workspace = true }
md-5 = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
hyper = { workspace = true }
http = { workspace = true }
rustls = { workspace = true }
tokio-rustls = { workspace = true }
rustls-pemfile = { workspace = true }
arc-swap = { workspace = true }
hyper-util = { workspace = true }
rcgen = { workspace = true }
time = { workspace = true }
base64 = { workspace = true }
reqwest = { workspace = true }
uuid = { workspace = true }
libc = { workspace = true }
redis = { workspace = true }
async-nats = { workspace = true }
rumqttc = { workspace = true }
sqlx-core = { workspace = true }
sqlx-postgres = { workspace = true }
sqlx-mysql = { workspace = true }
mongodb = { workspace = true }
lapin = { workspace = true }
tokio-executor-trait = { workspace = true }
tokio-reactor-trait = { workspace = true }
rdkafka = { workspace = true }
lettre = { workspace = true }
tonic = { workspace = true }
prost = { workspace = true }
bytes = { workspace = true }
tokio-stream = { workspace = true }
tokio-util = { workspace = true }
futures-core = { workspace = true }
futures-util = { workspace = true }
thiserror = { workspace = true }

[build-dependencies]
tonic-build = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
