"""Integration tests for presigned URL support (query-string SigV4).

These tests verify that presigned URLs generated by boto3 work correctly
against the Arca server for both GET and PUT operations.
"""

import hashlib
import json
import os
import time

import boto3
import pytest
import requests
from botocore.auth import S3SigV4Auth
from botocore.awsrequest import AWSRequest
from botocore.config import Config
from botocore.credentials import Credentials
from botocore.exceptions import ClientError


BUCKET = "test-presigned-bucket"


@pytest.fixture
def s3_client(endpoint_url):
    """boto3 S3 client configured with SigV4 for presigned URL generation."""
    kwargs = dict(
        endpoint_url=endpoint_url,
        aws_access_key_id=os.environ.get(
            "AWS_ACCESS_KEY_ID", "AKIAIOSFODNN7EXAMPLE"
        ),
        aws_secret_access_key=os.environ.get(
            "AWS_SECRET_ACCESS_KEY", "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
        ),
        region_name="us-east-1",
        config=Config(signature_version="s3v4"),
    )
    ca_bundle = os.environ.get("AWS_CA_BUNDLE")
    if endpoint_url.startswith("https://") and ca_bundle:
        kwargs["verify"] = ca_bundle
    return boto3.client("s3", **kwargs)


@pytest.fixture
def creds():
    """AWS credentials for SigV4 signing."""
    return Credentials(
        access_key=os.environ.get("AWS_ACCESS_KEY_ID", "AKIAIOSFODNN7EXAMPLE"),
        secret_key=os.environ.get(
            "AWS_SECRET_ACCESS_KEY", "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
        ),
    )


def signed_request(method, url, creds, data=None):
    """Make an HTTP request signed with SigV4."""
    headers = {}
    if data is not None:
        headers["Content-Type"] = "application/json"
        data = json.dumps(data) if isinstance(data, dict) else data

    aws_req = AWSRequest(method=method, url=url, data=data or "", headers=headers)
    S3SigV4Auth(creds, "s3", "us-east-1").add_auth(aws_req)
    return requests.request(
        method, url, headers=dict(aws_req.headers), data=data, timeout=10
    )


@pytest.fixture(autouse=True)
def setup_bucket(s3_client):
    """Create and clean up test bucket."""
    try:
        s3_client.create_bucket(Bucket=BUCKET)
    except ClientError:
        pass
    yield
    try:
        response = s3_client.list_objects_v2(Bucket=BUCKET)
        for obj in response.get("Contents", []):
            s3_client.delete_object(Bucket=BUCKET, Key=obj["Key"])
        s3_client.delete_bucket(Bucket=BUCKET)
    except ClientError:
        pass


class TestPresignedGet:
    """Tests for presigned GET URLs."""

    def test_presigned_get_basic(self, s3_client, endpoint_url):
        """Generate presigned GET URL and fetch with plain HTTP."""
        data = b"presigned get test"
        s3_client.put_object(Bucket=BUCKET, Key="presigned.txt", Body=data)

        url = s3_client.generate_presigned_url(
            "get_object",
            Params={"Bucket": BUCKET, "Key": "presigned.txt"},
            ExpiresIn=3600,
        )

        resp = requests.get(url, timeout=10)
        assert resp.status_code == 200
        assert resp.content == data

    def test_presigned_get_binary(self, s3_client, endpoint_url):
        """Presigned GET works with binary data."""
        data = bytes(range(256)) * 100
        s3_client.put_object(Bucket=BUCKET, Key="binary.bin", Body=data)

        url = s3_client.generate_presigned_url(
            "get_object",
            Params={"Bucket": BUCKET, "Key": "binary.bin"},
            ExpiresIn=3600,
        )

        resp = requests.get(url, timeout=10)
        assert resp.status_code == 200
        assert resp.content == data

    def test_presigned_get_with_special_chars(self, s3_client, endpoint_url):
        """Presigned GET works with special characters in key."""
        data = b"special chars test"
        key = "path/to/file with spaces.txt"
        s3_client.put_object(Bucket=BUCKET, Key=key, Body=data)

        url = s3_client.generate_presigned_url(
            "get_object",
            Params={"Bucket": BUCKET, "Key": key},
            ExpiresIn=3600,
        )

        resp = requests.get(url, timeout=10)
        assert resp.status_code == 200
        assert resp.content == data

    def test_presigned_get_nonexistent_key(self, s3_client, endpoint_url):
        """Presigned GET for non-existent key returns 404."""
        url = s3_client.generate_presigned_url(
            "get_object",
            Params={"Bucket": BUCKET, "Key": "does-not-exist.txt"},
            ExpiresIn=3600,
        )

        resp = requests.get(url, timeout=10)
        assert resp.status_code == 404

    def test_presigned_get_response_overrides(self, s3_client, endpoint_url):
        """Presigned GET with response-content-type override."""
        data = b"response override test"
        s3_client.put_object(
            Bucket=BUCKET,
            Key="override.txt",
            Body=data,
            ContentType="text/plain",
        )

        url = s3_client.generate_presigned_url(
            "get_object",
            Params={
                "Bucket": BUCKET,
                "Key": "override.txt",
                "ResponseContentType": "application/octet-stream",
                "ResponseContentDisposition": "attachment; filename=download.txt",
            },
            ExpiresIn=3600,
        )

        resp = requests.get(url, timeout=10)
        assert resp.status_code == 200
        assert resp.content == data
        assert resp.headers.get("Content-Type") == "application/octet-stream"
        assert "attachment" in resp.headers.get("Content-Disposition", "")


class TestPresignedPut:
    """Tests for presigned PUT URLs."""

    def test_presigned_put_basic(self, s3_client, endpoint_url):
        """Generate presigned PUT URL and upload with plain HTTP."""
        data = b"presigned put test"
        url = s3_client.generate_presigned_url(
            "put_object",
            Params={"Bucket": BUCKET, "Key": "put-presigned.txt"},
            ExpiresIn=3600,
        )

        resp = requests.put(url, data=data, timeout=10)
        assert resp.status_code == 200

        # Verify via normal GET
        get_resp = s3_client.get_object(Bucket=BUCKET, Key="put-presigned.txt")
        assert get_resp["Body"].read() == data

    def test_presigned_put_overwrite(self, s3_client, endpoint_url):
        """Presigned PUT overwrites existing object."""
        s3_client.put_object(Bucket=BUCKET, Key="overwrite.txt", Body=b"original")

        url = s3_client.generate_presigned_url(
            "put_object",
            Params={"Bucket": BUCKET, "Key": "overwrite.txt"},
            ExpiresIn=3600,
        )

        new_data = b"updated via presigned"
        resp = requests.put(url, data=new_data, timeout=10)
        assert resp.status_code == 200

        get_resp = s3_client.get_object(Bucket=BUCKET, Key="overwrite.txt")
        assert get_resp["Body"].read() == new_data


class TestPresignedSecurity:
    """Tests for presigned URL security and expiration."""

    def test_tampered_signature_rejected(self, s3_client, endpoint_url):
        """Tampering with the signature should be rejected."""
        data = b"tamper test"
        s3_client.put_object(Bucket=BUCKET, Key="tamper.txt", Body=data)

        url = s3_client.generate_presigned_url(
            "get_object",
            Params={"Bucket": BUCKET, "Key": "tamper.txt"},
            ExpiresIn=3600,
        )

        # Tamper with the signature
        tampered_url = url.replace("X-Amz-Signature=", "X-Amz-Signature=0000")
        resp = requests.get(tampered_url, timeout=10)
        assert resp.status_code == 403

    def test_tampered_path_rejected(self, s3_client, endpoint_url):
        """Changing the object key should be rejected."""
        s3_client.put_object(Bucket=BUCKET, Key="original.txt", Body=b"original")
        s3_client.put_object(Bucket=BUCKET, Key="other.txt", Body=b"other")

        url = s3_client.generate_presigned_url(
            "get_object",
            Params={"Bucket": BUCKET, "Key": "original.txt"},
            ExpiresIn=3600,
        )

        # Replace key in URL path
        tampered_url = url.replace("/original.txt", "/other.txt")
        resp = requests.get(tampered_url, timeout=10)
        assert resp.status_code == 403

    def test_max_expires_accepted(self, s3_client, endpoint_url):
        """Maximum expiry of 604800 seconds (7 days) is accepted."""
        data = b"max expires test"
        s3_client.put_object(Bucket=BUCKET, Key="maxexp.txt", Body=data)

        url = s3_client.generate_presigned_url(
            "get_object",
            Params={"Bucket": BUCKET, "Key": "maxexp.txt"},
            ExpiresIn=604800,
        )

        resp = requests.get(url, timeout=10)
        assert resp.status_code == 200
        assert resp.content == data


class TestPresignedHead:
    """Tests for presigned HEAD URLs."""

    def test_presigned_head(self, s3_client, endpoint_url):
        """Generate presigned HEAD URL and verify metadata."""
        data = b"head test data"
        s3_client.put_object(
            Bucket=BUCKET,
            Key="head.txt",
            Body=data,
            ContentType="text/plain",
        )

        url = s3_client.generate_presigned_url(
            "head_object",
            Params={"Bucket": BUCKET, "Key": "head.txt"},
            ExpiresIn=3600,
        )

        resp = requests.head(url, timeout=10)
        assert resp.status_code == 200
        assert resp.headers.get("Content-Length") == str(len(data))


class TestPresignedDelete:
    """Tests for presigned DELETE URLs."""

    def test_presigned_delete(self, s3_client, endpoint_url):
        """Generate presigned DELETE URL and delete object."""
        s3_client.put_object(Bucket=BUCKET, Key="delete-me.txt", Body=b"delete me")

        url = s3_client.generate_presigned_url(
            "delete_object",
            Params={"Bucket": BUCKET, "Key": "delete-me.txt"},
            ExpiresIn=3600,
        )

        resp = requests.delete(url, timeout=10)
        assert resp.status_code == 204

        # Verify object is deleted
        with pytest.raises(ClientError) as exc_info:
            s3_client.get_object(Bucket=BUCKET, Key="delete-me.txt")
        assert exc_info.value.response["Error"]["Code"] == "NoSuchKey"


class TestAdminPresign:
    """Tests for the admin presign endpoint."""

    def test_admin_presign_get(self, s3_client, endpoint_url, creds):
        """Admin presign endpoint generates a valid GET URL."""
        data = b"admin presign test"
        s3_client.put_object(Bucket=BUCKET, Key="admin-presign.txt", Body=data)

        url = f"{endpoint_url}/admin/presign"
        resp = signed_request(
            "POST",
            url,
            creds,
            data={"bucket": BUCKET, "key": "admin-presign.txt"},
        )
        assert resp.status_code == 200
        body = resp.json()
        assert "url" in body
        assert "expires_at" in body

        # Fetch the presigned URL
        get_resp = requests.get(body["url"], timeout=10)
        assert get_resp.status_code == 200
        assert get_resp.content == data

    def test_admin_presign_custom_expires(self, s3_client, endpoint_url, creds):
        """Admin presign endpoint respects custom expiry."""
        data = b"custom expires test"
        s3_client.put_object(Bucket=BUCKET, Key="custom-exp.txt", Body=data)

        url = f"{endpoint_url}/admin/presign"
        resp = signed_request(
            "POST",
            url,
            creds,
            data={"bucket": BUCKET, "key": "custom-exp.txt", "expires": 300},
        )
        assert resp.status_code == 200
        body = resp.json()
        assert "url" in body

        get_resp = requests.get(body["url"], timeout=10)
        assert get_resp.status_code == 200
        assert get_resp.content == data

    def test_admin_presign_put(self, s3_client, endpoint_url, creds):
        """Admin presign endpoint generates a valid PUT URL."""
        url = f"{endpoint_url}/admin/presign"
        resp = signed_request(
            "POST",
            url,
            creds,
            data={"bucket": BUCKET, "key": "admin-put.txt", "method": "PUT"},
        )
        assert resp.status_code == 200
        body = resp.json()
        assert "url" in body

        # Upload via presigned URL
        data = b"uploaded via admin presign"
        put_resp = requests.put(body["url"], data=data, timeout=10)
        assert put_resp.status_code == 200

        # Verify
        get_resp = s3_client.get_object(Bucket=BUCKET, Key="admin-put.txt")
        assert get_resp["Body"].read() == data

    def test_admin_presign_special_chars(self, s3_client, endpoint_url, creds):
        """Admin presign endpoint correctly encodes special characters in keys."""
        data = b"special chars via admin"
        key = "path/to/file with spaces & symbols.txt"
        s3_client.put_object(Bucket=BUCKET, Key=key, Body=data)

        url = f"{endpoint_url}/admin/presign"
        resp = signed_request(
            "POST",
            url,
            creds,
            data={"bucket": BUCKET, "key": key},
        )
        assert resp.status_code == 200
        body = resp.json()
        assert "url" in body
        # URL must not contain literal spaces
        assert " " not in body["url"]

        get_resp = requests.get(body["url"], timeout=10)
        assert get_resp.status_code == 200
        assert get_resp.content == data

    def test_admin_presign_endpoint_override(self, s3_client, endpoint_url, creds):
        """Admin presign endpoint respects the endpoint override field."""
        data = b"endpoint override test"
        s3_client.put_object(Bucket=BUCKET, Key="ep-override.txt", Body=data)

        url = f"{endpoint_url}/admin/presign"
        resp = signed_request(
            "POST",
            url,
            creds,
            data={
                "bucket": BUCKET,
                "key": "ep-override.txt",
                "endpoint": endpoint_url,
            },
        )
        assert resp.status_code == 200
        body = resp.json()
        assert body["url"].startswith(endpoint_url)

        get_resp = requests.get(body["url"], timeout=10)
        assert get_resp.status_code == 200
        assert get_resp.content == data
