services:
  arca:
    image: arca
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - arca-data:/data
    environment:
      - RUST_LOG=info
      - ARCA_ROOT_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE
      - ARCA_ROOT_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY

  unit-test:
    image: arca-unit-test
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: dev
    profiles:
      - test

  test:
    image: arca-test
    build:
      context: ..
      dockerfile: docker/Dockerfile.test
    environment:
      - ARCA_ENDPOINT=http://arca:9000
      - AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE
      - AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    depends_on:
      - arca
    profiles:
      - test

volumes:
  arca-data:
