FROM python:3.12-slim

WORKDIR /tests

COPY tests/integration/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY tests/ /tests/

ENTRYPOINT ["pytest"]
CMD ["integration/", "-v"]
