[DEFAULT]
host = arca
port = 9000
is_secure = false

[fixtures]
bucket prefix = arca-test-{random}-
iam name prefix = s3-tests-
iam path prefix = /s3-tests/

[s3 main]
display_name = M. Tester
user_id = testid
email = tester@arca.local
access_key = AKIAIOSFODNN7EXAMPLE
secret_key = wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY

[s3 alt]
display_name = A. Tester
user_id = testaltid
email = alttester@arca.local
access_key = AKIAIOSFODNN7EXAMPLE
secret_key = wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY

[s3 tenant]
display_name = T. Tester
user_id = testtenantid
email = tenanttester@arca.local
access_key = AKIAIOSFODNN7EXAMPLE
secret_key = wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
tenant = testx

[iam]
email = iam@arca.local
user_id = iamtestid
access_key = AKIAIOSFODNN7EXAMPLE
secret_key = wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
display_name = IAM Tester

[iam root]
access_key = AKIAIOSFODNN7EXAMPLE
secret_key = wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
user_id = iamrootid
email = iamroot@arca.local

[iam alt root]
access_key = AKIAIOSFODNN7EXAMPLE
secret_key = wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
user_id = iamaltid
email = iamalt@arca.local

[webidentity]
token = placeholder
aud = placeholder
sub = placeholder
azp = placeholder
user_token = placeholder
thumbprint = placeholder
KC_REALM = placeholder
